name: CI build
on: [ push, pull_request ]
jobs:
    symfony:
        name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
                php-versions: [ '7.3', '7.4' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    ini-values: memory_limit=-1
                    tools: composer:v1
            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Run Tests
                run: vendor/bin/phpunit
